// <auto-generated />
using System;
using Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(RestauranteDisponibilidadContext))]
    [Migration("20251127185054_AddRolToUsuario")]
    partial class AddRolToUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Calificacion", b =>
                {
                    b.Property<uint>("IdCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdCalificacion"));

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("IdPedido")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("IdPedidoNavigationIdPedido")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("IdPlato")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("IdPlatoNavigationIdPlato")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("IdUsuario")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("IdUsuarioNavigationIdUsuario")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Puntuacion")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("IdCalificacion");

                    b.HasIndex("IdPedidoNavigationIdPedido");

                    b.HasIndex("IdPlatoNavigationIdPlato");

                    b.HasIndex("IdUsuarioNavigationIdUsuario");

                    b.ToTable("Calificacions");
                });

            modelBuilder.Entity("Api.Models.Categoriaplato", b =>
                {
                    b.Property<uint>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("idCategoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCategoria")
                        .HasName("PRIMARY");

                    b.ToTable("categoriaplato", (string)null);
                });

            modelBuilder.Entity("Api.Models.Configuracionrestaurante", b =>
                {
                    b.Property<uint>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdConfiguracion"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdConfiguracion");

                    b.ToTable("Configuracionrestaurantes");
                });

            modelBuilder.Entity("Api.Models.Detallepedido", b =>
                {
                    b.Property<uint>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("idDetallePedido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdDetallePedido"));

                    b.Property<sbyte>("Cantidad")
                        .HasColumnType("tinyint");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("IdPedido")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPedido");

                    b.Property<uint>("IdPlato")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPlato");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDetallePedido")
                        .HasName("PRIMARY");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdPlato");

                    b.ToTable("detallepedido", (string)null);
                });

            modelBuilder.Entity("Api.Models.Estadopedido", b =>
                {
                    b.Property<uint>("IdEstadoPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("idEstadoPedido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdEstadoPedido"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEstadoPedido")
                        .HasName("PRIMARY");

                    b.ToTable("estadopedido", (string)null);
                });

            modelBuilder.Entity("Api.Models.Historialdisponibilidad", b =>
                {
                    b.Property<uint>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdHistorial"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("IdPlato")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("IdPlatoNavigationIdPlato")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Motivo")
                        .HasColumnType("longtext");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdPlatoNavigationIdPlato");

                    b.ToTable("Historialdisponibilidads");
                });

            modelBuilder.Entity("Api.Models.Horariorestaurante", b =>
                {
                    b.Property<uint>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdHorario"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("DiaSemana")
                        .HasColumnType("tinyint unsigned");

                    b.Property<TimeOnly>("HoraApertura")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("HoraCierre")
                        .HasColumnType("time(6)");

                    b.HasKey("IdHorario");

                    b.ToTable("Horariorestaurantes");
                });

            modelBuilder.Entity("Api.Models.Ingrediente", b =>
                {
                    b.Property<uint>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdIngrediente"));

                    b.Property<bool>("EsCritico")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdIngrediente");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Api.Models.Mesa", b =>
                {
                    b.Property<uint>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("idMesa");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdMesa"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<sbyte>("Capacidad")
                        .HasColumnType("tinyint");

                    b.Property<string>("NumeroMesa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdMesa")
                        .HasName("PRIMARY");

                    b.ToTable("mesa", (string)null);
                });

            modelBuilder.Entity("Api.Models.Metodopago", b =>
                {
                    b.Property<uint>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdMetodoPago"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TipoMedioPago")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdMetodoPago");

                    b.ToTable("Metodopago");
                });

            modelBuilder.Entity("Api.Models.Pedido", b =>
                {
                    b.Property<uint>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPedido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdPedido"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EsPreOrden")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaHoraEntregaEstimada")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaHoraEntregaReal")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHoraPedido")
                        .HasColumnType("datetime");

                    b.Property<uint>("IdEstadoPedido")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idEstadoPedido");

                    b.Property<uint?>("IdMetodoPago")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idMetodoPago");

                    b.Property<uint?>("IdReserva")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idReserva");

                    b.Property<uint>("IdUsuario")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idUsuario");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedido")
                        .HasName("PRIMARY");

                    b.HasIndex("IdEstadoPedido");

                    b.HasIndex("IdMetodoPago");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdUsuario");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("Api.Models.Plato", b =>
                {
                    b.Property<uint>("IdPlato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPlato");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdPlato"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("EsMenuDelDia")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("IdCategoria")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idCategoria");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ImagenURL");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<uint>("TiempoPreparacion")
                        .HasColumnType("int unsigned");

                    b.HasKey("IdPlato")
                        .HasName("PRIMARY");

                    b.HasIndex("IdCategoria");

                    b.ToTable("plato", (string)null);
                });

            modelBuilder.Entity("Api.Models.Platoingrediente", b =>
                {
                    b.Property<uint>("IdPlato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdPlato"));

                    b.Property<decimal>("CantidadNecesaria")
                        .HasColumnType("decimal(65,30)");

                    b.Property<uint>("IdIngrediente")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("IdIngredienteNavigationIdIngrediente")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("IdPlatoNavigationIdPlato")
                        .HasColumnType("int unsigned");

                    b.HasKey("IdPlato");

                    b.HasIndex("IdIngredienteNavigationIdIngrediente");

                    b.HasIndex("IdPlatoNavigationIdPlato");

                    b.ToTable("Platoingredientes");
                });

            modelBuilder.Entity("Api.Models.Reserva", b =>
                {
                    b.Property<uint>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("idReserva");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdReserva"));

                    b.Property<sbyte>("CantidadPersonas")
                        .HasColumnType("tinyint");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime");

                    b.Property<uint?>("IdMesa")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idMesa");

                    b.Property<uint>("IdUsuario")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idUsuario");

                    b.HasKey("IdReserva")
                        .HasName("PRIMARY");

                    b.HasIndex("IdMesa");

                    b.HasIndex("IdUsuario");

                    b.ToTable("reserva", (string)null);
                });

            modelBuilder.Entity("Api.Models.Usuario", b =>
                {
                    b.Property<uint>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("idUsuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("cliente");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdUsuario")
                        .HasName("PRIMARY");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Api.Models.Calificacion", b =>
                {
                    b.HasOne("Api.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("Calificacions")
                        .HasForeignKey("IdPedidoNavigationIdPedido");

                    b.HasOne("Api.Models.Plato", "IdPlatoNavigation")
                        .WithMany("Calificacions")
                        .HasForeignKey("IdPlatoNavigationIdPlato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdUsuarioNavigationIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdPlatoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api.Models.Detallepedido", b =>
                {
                    b.HasOne("Api.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("Detallepedidos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_DetallePedido_Pedido");

                    b.HasOne("Api.Models.Plato", "IdPlatoNavigation")
                        .WithMany("Detallepedidos")
                        .HasForeignKey("IdPlato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_DetallePedido_Plato");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdPlatoNavigation");
                });

            modelBuilder.Entity("Api.Models.Historialdisponibilidad", b =>
                {
                    b.HasOne("Api.Models.Plato", "IdPlatoNavigation")
                        .WithMany("Historialdisponibilidads")
                        .HasForeignKey("IdPlatoNavigationIdPlato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPlatoNavigation");
                });

            modelBuilder.Entity("Api.Models.Pedido", b =>
                {
                    b.HasOne("Api.Models.Estadopedido", "IdEstadoPedidoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdEstadoPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_Pedido_EstadoPedido");

                    b.HasOne("Api.Models.Metodopago", "IdMetodoPagoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdMetodoPago")
                        .HasConstraintName("fk_Pedido_MetodoPago");

                    b.HasOne("Api.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdReserva")
                        .HasConstraintName("fk_Pedido_Reserva");

                    b.HasOne("Api.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_Pedido_Usuario");

                    b.Navigation("IdEstadoPedidoNavigation");

                    b.Navigation("IdMetodoPagoNavigation");

                    b.Navigation("IdReservaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api.Models.Plato", b =>
                {
                    b.HasOne("Api.Models.Categoriaplato", "IdCategoriaNavigation")
                        .WithMany("Platos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_Plato_Categoria");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("Api.Models.Platoingrediente", b =>
                {
                    b.HasOne("Api.Models.Ingrediente", "IdIngredienteNavigation")
                        .WithMany("Platoingredientes")
                        .HasForeignKey("IdIngredienteNavigationIdIngrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Plato", "IdPlatoNavigation")
                        .WithMany("Platoingredientes")
                        .HasForeignKey("IdPlatoNavigationIdPlato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdIngredienteNavigation");

                    b.Navigation("IdPlatoNavigation");
                });

            modelBuilder.Entity("Api.Models.Reserva", b =>
                {
                    b.HasOne("Api.Models.Mesa", "IdMesaNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdMesa")
                        .HasConstraintName("fk_Reserva_Mesa");

                    b.HasOne("Api.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_Reserva_Usuario");

                    b.Navigation("IdMesaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api.Models.Categoriaplato", b =>
                {
                    b.Navigation("Platos");
                });

            modelBuilder.Entity("Api.Models.Estadopedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Api.Models.Ingrediente", b =>
                {
                    b.Navigation("Platoingredientes");
                });

            modelBuilder.Entity("Api.Models.Mesa", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Api.Models.Metodopago", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Api.Models.Pedido", b =>
                {
                    b.Navigation("Calificacions");

                    b.Navigation("Detallepedidos");
                });

            modelBuilder.Entity("Api.Models.Plato", b =>
                {
                    b.Navigation("Calificacions");

                    b.Navigation("Detallepedidos");

                    b.Navigation("Historialdisponibilidads");

                    b.Navigation("Platoingredientes");
                });

            modelBuilder.Entity("Api.Models.Reserva", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Api.Models.Usuario", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("Pedidos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
